apiVersion: apps/v1
kind: Deployment
metadata:
  name: busyhttp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busyhttp
  template:
    metadata:
      labels:
        app: busyhttp
    spec:
      containers:
        - name: busyhttp
          image: ghcr.io/platformfix/busyhttp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            timeoutSeconds: 5
