name: k8s-validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: k8s-validate-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install kubeconform
        env:
          KUBECONFORM_VERSION: v0.8.0
        run: |
          curl -sSLO "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz"
          curl -sSLO "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/CHECKSUMS"
          grep " kubeconform-linux-amd64.tar.gz\$" CHECKSUMS | sha256sum -c -
          tar xzf kubeconform-linux-amd64.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/
      - run: kubeconform -strict kubernetes/*.yaml
